# Generated by Django 5.0.1 on 2024-01-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("currency", models.CharField(max_length=4)),
                ("exchange_rate", models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
    ]
